# Generated by Django 3.2.8 on 2021-11-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date']},
        ),
    ]
